import type { Match, Message, Profile } from "./types";

export const currentUser = {
  id: "me",
  name: "Алекс",
  age: 28,
  photo: "/me.webp",
};

export const profiles: Profile[] = [
  {
    id: "u_01",
    name: "София",
    age: 26,
    gender: "female",
    bio: "Дизайнер интерьеров, люблю утренний кофе и долгие прогулки по городу. Ищу того, с кем можно разделить тишину и приключения.",
    photos: [
      { id: "p1", url: "/profiles/sofia-1.webp" },
      { id: "p2", url: "/profiles/sofia-2.webp" },
      { id: "p3", url: "/profiles/sofia-3.webp" },
    ],
    occupation: "Дизайнер интерьеров",
    city: "Москва",
    distanceKm: 2,
    verified: true,
    online: true,
    height: 170,
    lookingFor: ["male"],
    maxDistanceKm: 25,
    ageRange: [25, 35],
  },
  {
    id: "u_02",
    name: "Михаил",
    age: 31,
    gender: "male",
    bio: "Архитектор. Стройка, чертёж, кофе по утрам. Выходные — горы или море, в зависимости от сезона.",
    photos: [
      { id: "p1", url: "/profiles/mikhail-1.webp" },
      { id: "p2", url: "/profiles/mikhail-2.webp" },
    ],
    occupation: "Архитектор",
    city: "Москва",
    distanceKm: 5,
    verified: true,
    online: false,
    lastSeen: "был(а) 2 ч назад",
    height: 184,
    lookingFor: ["female"],
    maxDistanceKm: 30,
    ageRange: [24, 32],
  },
  {
    id: "u_03",
    name: "Анна",
    age: 24,
    gender: "female",
    bio: "Маркетолог, фанат скейтбординга и независимой музыки. Если ты умеешь играть на гитаре — у меня уже бабочки.",
    photos: [
      { id: "p1", url: "/profiles/anna-1.webp" },
      { id: "p2", url: "/profiles/anna-2.webp" },
      { id: "p3", url: "/profiles/anna-3.webp" },
    ],
    occupation: "Маркетолог",
    city: "Москва",
    distanceKm: 4,
    verified: false,
    online: true,
    height: 165,
    lookingFor: ["male"],
    maxDistanceKm: 20,
    ageRange: [24, 33],
  },
  {
    id: "u_04",
    name: "Давид",
    age: 29,
    gender: "male",
    bio: "Шеф в небольшом ресторане. Готовлю для друзей лучше, чем для гостей. Веду блог о ферментации.",
    photos: [
      { id: "p1", url: "/profiles/david-1.webp" },
      { id: "p2", url: "/profiles/david-2.webp" },
    ],
    occupation: "Шеф-повар",
    city: "Москва",
    distanceKm: 7,
    verified: true,
    online: true,
    height: 181,
    lookingFor: ["female", "nonbinary"],
    maxDistanceKm: 40,
    ageRange: [23, 34],
  },
  {
    id: "u_05",
    name: "Ксения",
    age: 27,
    gender: "female",
    bio: "Преподаватель йоги и немного астроном-любитель. Покажу Сатурн в телескоп, если не испугаешься холода.",
    photos: [
      { id: "p1", url: "/profiles/ksenia-1.webp" },
      { id: "p2", url: "/profiles/ksenia-2.webp" },
      { id: "p3", url: "/profiles/ksenia-3.webp" },
    ],
    occupation: "Преподаватель йоги",
    city: "Москва",
    distanceKm: 3,
    verified: true,
    online: false,
    lastSeen: "был(а) вчера",
    height: 168,
    lookingFor: ["male"],
    maxDistanceKm: 15,
    ageRange: [26, 36],
  },
  {
    id: "u_06",
    name: "Артём",
    age: 30,
    gender: "male",
    bio: "Разработчик, играю на виниле, выращиваю перец чили на балконе. Ищу соулмейта по настолкам.",
    photos: [
      { id: "p1", url: "/profiles/artem-1.webp" },
      { id: "p2", url: "/profiles/artem-2.webp" },
    ],
    occupation: "Frontend-разработчик",
    city: "Москва",
    distanceKm: 6,
    verified: false,
    online: true,
    height: 178,
    lookingFor: ["female"],
    maxDistanceKm: 25,
    ageRange: [24, 31],
  },
  {
    id: "u_07",
    name: "Мария",
    age: 25,
    gender: "female",
    bio: "Журналист, пишу про культуру. Люблю музеи, джаз и спонтанные поездки на электричке.",
    photos: [
      { id: "p1", url: "/profiles/maria-1.webp" },
      { id: "p2", url: "/profiles/maria-2.webp" },
      { id: "p3", url: "/profiles/maria-3.webp" },
    ],
    occupation: "Журналист",
    city: "Москва",
    distanceKm: 8,
    verified: true,
    online: true,
    height: 172,
    lookingFor: ["male"],
    maxDistanceKm: 30,
    ageRange: [25, 34],
  },
  {
    id: "u_08",
    name: "Илья",
    age: 33,
    gender: "male",
    bio: "Хирург. Руки золотые, характер терпеливый. В свободное время — рыбалка и хорошие книги.",
    photos: [
      { id: "p1", url: "/profiles/ilya-1.webp" },
      { id: "p2", url: "/profiles/ilya-2.webp" },
    ],
    occupation: "Хирург",
    city: "Москва",
    distanceKm: 9,
    verified: true,
    online: false,
    lastSeen: "был(а) 30 мин назад",
    height: 187,
    lookingFor: ["female"],
    maxDistanceKm: 20,
    ageRange: [24, 32],
  },
];

export const initialMatches: Match[] = [
  {
    id: "m_01",
    profileId: "u_03",
    createdAt: "2025-01-15T18:42:00Z",
    unread: 2,
    lastMessage: {
      id: "msg_03",
      matchId: "m_01",
      authorId: "u_03",
      text: "Ты серьёзно про гитару? 😏",
      createdAt: "2025-01-15T19:10:00Z",
      read: false,
    },
  },
  {
    id: "m_02",
    profileId: "u_05",
    createdAt: "2025-01-14T12:00:00Z",
    unread: 0,
    lastMessage: {
      id: "msg_06",
      matchId: "m_02",
      authorId: "me",
      text: "Договорились на субботу 🌌",
      createdAt: "2025-01-15T10:24:00Z",
      read: true,
    },
  },
  {
    id: "m_03",
    profileId: "u_07",
    createdAt: "2025-01-12T20:11:00Z",
    unread: 1,
    lastMessage: {
      id: "msg_07",
      matchId: "m_03",
      authorId: "u_07",
      text: "Слушай, я как раз иду в Пушкинский в субботу — составишь компанию?",
      createdAt: "2025-01-15T14:02:00Z",
      read: false,
    },
  },
  {
    id: "m_04",
    profileId: "u_01",
    createdAt: "2025-01-10T09:30:00Z",
    unread: 0,
    lastMessage: {
      id: "msg_09",
      matchId: "m_04",
      authorId: "u_01",
      text: "Спасибо за совет с кофейней ☕️",
      createdAt: "2025-01-13T22:15:00Z",
      read: true,
    },
  },
];

export const initialMessages: Record<string, Message[]> = {
  m_01: [
    {
      id: "msg_01",
      matchId: "m_01",
      authorId: "me",
      text: "Привет! Вижу, ты тоже катаешь 🛹",
      createdAt: "2025-01-15T18:42:00Z",
      read: true,
    },
    {
      id: "msg_02",
      matchId: "m_01",
      authorId: "u_03",
      text: "Привет! Да, без этого уже не могу 😄 А ты давно?",
      createdAt: "2025-01-15T18:55:00Z",
      read: true,
    },
    {
      id: "msg_03",
      matchId: "m_01",
      authorId: "u_03",
      text: "Ты серьёзно про гитару? 😏",
      createdAt: "2025-01-15T19:10:00Z",
      read: false,
    },
  ],
  m_02: [
    {
      id: "msg_04",
      matchId: "m_02",
      authorId: "u_05",
      text: "У тебя в профиле астрономия — это серьёзно?",
      createdAt: "2025-01-14T12:00:00Z",
      read: true,
    },
    {
      id: "msg_05",
      matchId: "m_02",
      authorId: "me",
      text: "Абсолютно. Телескоп уже достал с балкона 🤓",
      createdAt: "2025-01-14T12:14:00Z",
      read: true,
    },
    {
      id: "msg_06",
      matchId: "m_02",
      authorId: "me",
      text: "Договорились на субботу 🌌",
      createdAt: "2025-01-15T10:24:00Z",
      read: true,
    },
  ],
  m_03: [
    {
      id: "msg_07",
      matchId: "m_03",
      authorId: "u_07",
      text: "Слушай, я как раз иду в Пушкинский в субботу — составишь компанию?",
      createdAt: "2025-01-15T14:02:00Z",
      read: false,
    },
  ],
  m_04: [
    {
      id: "msg_08",
      matchId: "m_04",
      authorId: "me",
      text: "Знаешь отличную кофейню на Патриарших?",
      createdAt: "2025-01-13T21:50:00Z",
      read: true,
    },
    {
      id: "msg_09",
      matchId: "m_04",
      authorId: "u_01",
      text: "Спасибо за совет с кофейней ☕️",
      createdAt: "2025-01-13T22:15:00Z",
      read: true,
    },
  ],
};

export const likedByProfiles: Profile[] = [profiles[2], profiles[4], profiles[6]];
